# Form implementation generated from reading ui file 'склад.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1076, 687)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mainLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.mainLayout.setObjectName("mainLayout")
        self.navPanel = QtWidgets.QWidget(parent=self.centralwidget)
        self.navPanel.setMinimumSize(QtCore.QSize(180, 0))
        self.navPanel.setMaximumSize(QtCore.QSize(200, 16777215))
        self.navPanel.setStyleSheet("QWidget#navPanel {\n"
"    background-color: #f8f9fa;\n"
"    border-right: 1px solid #dee2e6;\n"
"}")
        self.navPanel.setObjectName("navPanel")
        self.navLayout = QtWidgets.QVBoxLayout(self.navPanel)
        self.navLayout.setObjectName("navLayout")
        self.appTitle = QtWidgets.QLabel(parent=self.navPanel)
        self.appTitle.setStyleSheet("font-size: 16px; font-weight: bold; color: #2c3e50; padding: 15px;")
        self.appTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.appTitle.setObjectName("appTitle")
        self.navLayout.addWidget(self.appTitle)
        self.storage = QtWidgets.QPushButton(parent=self.navPanel)
        self.storage.setStyleSheet("QPushButton {\n"
"    text-align: left;\n"
"    padding: 12px 15px;\n"
"    border: none;\n"
"    border-left: 3px solid transparent;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #e9ecef;\n"
"}\n"
"QPushButton:checked {\n"
"    background-color: #007bff;\n"
"    color: white;\n"
"    border-left: 3px solid #0056b3;\n"
"}")
        self.storage.setCheckable(True)
        self.storage.setChecked(True)
        self.storage.setObjectName("storage")
        self.navLayout.addWidget(self.storage)
        self.purchase = QtWidgets.QPushButton(parent=self.navPanel)
        self.purchase.setStyleSheet("QPushButton {\n"
"    text-align: left;\n"
"    padding: 12px 15px;\n"
"    border: none;\n"
"    border-left: 3px solid transparent;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #e9ecef;\n"
"}\n"
"QPushButton:checked {\n"
"    background-color: #007bff;\n"
"    color: white;\n"
"    border-left: 3px solid #0056b3;\n"
"}")
        self.purchase.setCheckable(True)
        self.purchase.setObjectName("purchase")
        self.navLayout.addWidget(self.purchase)
        self.sales = QtWidgets.QPushButton(parent=self.navPanel)
        self.sales.setStyleSheet("QPushButton {\n"
"    text-align: left;\n"
"    padding: 12px 15px;\n"
"    border: none;\n"
"    border-left: 3px solid transparent;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #e9ecef;\n"
"}\n"
"QPushButton:checked {\n"
"    background-color: #007bff;\n"
"    color: white;\n"
"    border-left: 3px solid #0056b3;\n"
"}")
        self.sales.setCheckable(True)
        self.sales.setObjectName("sales")
        self.navLayout.addWidget(self.sales)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.navLayout.addItem(spacerItem)
        self.mainLayout.addWidget(self.navPanel)
        self.contentPanel = QtWidgets.QWidget(parent=self.centralwidget)
        self.contentPanel.setObjectName("contentPanel")
        self.contentLayout = QtWidgets.QVBoxLayout(self.contentPanel)
        self.contentLayout.setObjectName("contentLayout")
        self.headerLayout = QtWidgets.QHBoxLayout()
        self.headerLayout.setObjectName("headerLayout")
        self.sectionTitle = QtWidgets.QLabel(parent=self.contentPanel)
        self.sectionTitle.setStyleSheet("font-size: 20px; font-weight: bold; color: #2c3e50;")
        self.sectionTitle.setObjectName("sectionTitle")
        self.headerLayout.addWidget(self.sectionTitle)
        self.contentLayout.addLayout(self.headerLayout)
        self.searchLayout = QtWidgets.QHBoxLayout()
        self.searchLayout.setObjectName("searchLayout")
        self.searchInput = QtWidgets.QLineEdit(parent=self.contentPanel)
        self.searchInput.setStyleSheet("QLineEdit {\n"
"    padding: 8px 12px;\n"
"    border: 1px solid #ced4da;\n"
"    border-radius: 4px;\n"
"    font-size: 14px;\n"
"}\n"
"QLineEdit:focus {\n"
"    border-color: #007bff;\n"
"}")
        self.searchInput.setObjectName("searchInput")
        self.searchLayout.addWidget(self.searchInput)
        self.search_button = QtWidgets.QPushButton(parent=self.contentPanel)
        self.search_button.setStyleSheet("QPushButton {\n"
"    padding: 8px 16px;\n"
"    background-color: #007bff;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #0056b3;\n"
"}")
        self.search_button.setObjectName("search_button")
        self.searchLayout.addWidget(self.search_button)
        self.filter = QtWidgets.QPushButton(parent=self.contentPanel)
        self.filter.setStyleSheet("QPushButton {\n"
"    padding: 8px 16px;\n"
"    background-color: #6c757d;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #545b62;\n"
"}")
        self.filter.setObjectName("filter")
        self.searchLayout.addWidget(self.filter)
        self.contentLayout.addLayout(self.searchLayout)
        self.actionsGroup = QtWidgets.QGroupBox(parent=self.contentPanel)
        self.actionsGroup.setObjectName("actionsGroup")
        self.actionsLayout = QtWidgets.QHBoxLayout(self.actionsGroup)
        self.actionsLayout.setObjectName("actionsLayout")
        self.add = QtWidgets.QPushButton(parent=self.actionsGroup)
        self.add.setStyleSheet("QPushButton {\n"
"    padding: 8px 16px;\n"
"    background-color: #28a745;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #218838;\n"
"}")
        self.add.setObjectName("add")
        self.actionsLayout.addWidget(self.add)
        self.edit = QtWidgets.QPushButton(parent=self.actionsGroup)
        self.edit.setStyleSheet("QPushButton {\n"
"    padding: 8px 16px;\n"
"    background-color: #ffc107;\n"
"    color: #212529;\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #e0a800;\n"
"}")
        self.edit.setObjectName("edit")
        self.actionsLayout.addWidget(self.edit)
        self.copy = QtWidgets.QPushButton(parent=self.actionsGroup)
        self.copy.setStyleSheet("QPushButton {\n"
"    padding: 8px 16px;\n"
"    background-color: #17a2b8;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #138496;\n"
"}")
        self.copy.setObjectName("copy")
        self.actionsLayout.addWidget(self.copy)
        self.delete_2 = QtWidgets.QPushButton(parent=self.actionsGroup)
        self.delete_2.setStyleSheet("QPushButton {\n"
"    padding: 8px 16px;\n"
"    background-color: #dc3545;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #c82333;\n"
"}")
        self.delete_2.setObjectName("delete_2")
        self.actionsLayout.addWidget(self.delete_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.actionsLayout.addItem(spacerItem1)
        self.new_sale = QtWidgets.QPushButton(parent=self.actionsGroup)
        self.new_sale.setStyleSheet("QPushButton {\n"
"    padding: 8px 16px;\n"
"    background-color: #007bff;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #0056b3;\n"
"}")
        self.new_sale.setObjectName("new_sale")
        self.actionsLayout.addWidget(self.new_sale)
        self.pushButton = QtWidgets.QPushButton(parent=self.actionsGroup)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    padding: 8px 16px;\n"
"    background-color: #6c757d;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #545b62;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.actionsLayout.addWidget(self.pushButton)
        self.contentLayout.addWidget(self.actionsGroup)
        self.tableView = QtWidgets.QTableView(parent=self.contentPanel)
        self.tableView.setStyleSheet("QTableView {\n"
"    alternate-background-color: #f8f9fa;\n"
"    gridline-color: #dee2e6;\n"
"    selection-background-color: #007bff;\n"
"}\n"
"QTableView::item {\n"
"    padding: 8px;\n"
"    border-bottom: 1px solid #dee2e6;\n"
"}\n"
"QHeaderView::section {\n"
"    background-color: #e9ecef;\n"
"    padding: 8px;\n"
"    border: none;\n"
"    border-right: 1px solid #dee2e6;\n"
"    font-weight: bold;\n"
"}")
        self.tableView.setAlternatingRowColors(True)
        self.tableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tableView.setSortingEnabled(True)
        self.tableView.setObjectName("tableView")
        self.contentLayout.addWidget(self.tableView)
        self.footerLayout = QtWidgets.QHBoxLayout()
        self.footerLayout.setObjectName("footerLayout")
        self.statsLabel = QtWidgets.QLabel(parent=self.contentPanel)
        self.statsLabel.setStyleSheet("color: #6c757d; font-size: 12px;")
        self.statsLabel.setObjectName("statsLabel")
        self.footerLayout.addWidget(self.statsLabel)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.footerLayout.addItem(spacerItem2)
        self.contentLayout.addLayout(self.footerLayout)
        self.mainLayout.addWidget(self.contentPanel)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1076, 24))
        self.menubar.setStyleSheet("background-color: #343a40; color: white;")
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(parent=self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setStyleSheet("background-color: #e9ecef; color: #6c757d;")
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Учет товаров магазина"))
        self.appTitle.setText(_translate("MainWindow", "МАГАЗИН"))
        self.storage.setText(_translate("MainWindow", "📦 СКЛАД"))
        self.purchase.setText(_translate("MainWindow", "🛒 ЗАКУПКА"))
        self.sales.setText(_translate("MainWindow", "💰 ПРОДАЖИ"))
        self.sectionTitle.setText(_translate("MainWindow", "Склад товаров"))
        self.searchInput.setPlaceholderText(_translate("MainWindow", "Поиск по названию, артикулу..."))
        self.search_button.setText(_translate("MainWindow", "🔍 Найти"))
        self.filter.setText(_translate("MainWindow", "Фильтры"))
        self.actionsGroup.setTitle(_translate("MainWindow", "Управление товарами"))
        self.add.setText(_translate("MainWindow", "➕ Добавить"))
        self.edit.setText(_translate("MainWindow", "Изменить"))
        self.copy.setText(_translate("MainWindow", "📋 Копировать"))
        self.delete_2.setText(_translate("MainWindow", "🗑️ Удалить"))
        self.new_sale.setText(_translate("MainWindow", "💰 Новая продажа"))
        self.pushButton.setText(_translate("MainWindow", "📝 Списать"))
        self.statsLabel.setText(_translate("MainWindow", "Всего: 125 товаров | Сумма: 458 750 ₽"))
        self.menu.setTitle(_translate("MainWindow", "Файл"))